# Generated by Django 2.0 on 2018-01-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_post',
            new_name='Blog',
        ),
    ]
