# Generated by Django 2.0 on 2018-01-19 18:38

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=50, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('product_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_three', to='products.Product')),
                ('product_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_two', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='NavbarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='navigation')),
            ],
        ),
    ]
