# Generated by Django 2.0 on 2018-01-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='HomeFeatured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('product_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_three', to='products.Category')),
                ('product_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_two', to='products.Category')),
            ],
        ),
    ]
