# Generated by Django 2.0 on 2018-01-25 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_four', to='products.Category')),
                ('category_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('category_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_three', to='products.Category')),
                ('category_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_two', to='products.Category')),
            ],
        ),
    ]
