# Generated by Django 2.0 on 2018-01-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homecollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
