# Generated by Django 2.0 on 2018-01-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180117_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecarousel',
            old_name='category',
            new_name='home_carousel',
        ),
    ]
