# Generated by Django 2.0 on 2018-01-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180117_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecarousel',
            old_name='home_carousel',
            new_name='category',
        ),
    ]
