# Generated by Django 2.0 on 2018-01-17 17:25

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180117_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=50, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
