# Generated by Django 2.0 on 2018-01-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='navigation')),
            ],
        ),
    ]
