# Generated by Django 2.0 on 2018-01-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180117_1628'),
        ('home', '0007_navbarimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeFeatured',
            new_name='HomeFeature',
        ),
    ]
