# Generated by Django 2.0 on 2018-01-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=8)),
                ('additional_note', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.CustomerCart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.CustomerOrder')),
            ],
        ),
        migrations.AddField(
            model_name='customercart',
            name='customer_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.CustomerOrder'),
        ),
    ]
