# Generated by Django 2.0 on 2018-01-24 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_customercart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercart',
            name='customer_order',
        ),
        migrations.RemoveField(
            model_name='customerproduct',
            name='customer_order',
        ),
        migrations.RemoveField(
            model_name='customerproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='CustomerCart',
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
        migrations.DeleteModel(
            name='CustomerProduct',
        ),
    ]
