# Generated by Django 2.0 on 2018-01-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
