# Generated by Django 2.0 on 2018-01-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180124_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=10),
            preserve_default=False,
        ),
    ]
