# Generated by Django 2.0 on 2018-01-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_customerproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='additional_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
