# Generated by Django 2.0 on 2018-01-25 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180125_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='customer_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.CustomerOrder'),
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.Product'),
        ),
    ]
