# Generated by Django 2.0 on 2018-02-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_customerorder_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
